sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: Team30-ISA
  token: ce7510347ae572b6e1bdc0830510ecb30fddc2b3

script:
  - ./mvnw clean install -DskipTests=false -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=tim30 -Dsonar.organization=tim30 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=ce7510347ae572b6e1bdc0830510ecb30fddc2b3

dist: trusty

deploy:
  provider: heroku
  api_key: 5f3d1fec-e045-4b17-8356-29dcd21c2cb4
  app: apoteka-isa
