package isa.apoteka.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrandService.proto

public final class ErrandServiceOuterClass {
  private ErrandServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrandMedication_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrandMedication_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrandMedicationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrandMedicationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrandMedicationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrandMedicationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ErrandService.proto\"!\n\rErrandRequest\022\020" +
      "\n\010deadline\030\001 \001(\t\"\034\n\016ErrandResponse\022\n\n\002id" +
      "\030\001 \001(\005\"P\n\020ErrandMedication\022\n\n\002id\030\001 \001(\005\022\014" +
      "\n\004name\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\022\020\n\010errand" +
      "Id\030\004 \001(\005\"G\n\027ErrandMedicationRequest\022,\n\021e" +
      "rrandMedications\030\001 \003(\0132\021.ErrandMedicatio" +
      "n\",\n\030ErrandMedicationResponse\022\020\n\010respons" +
      "e\030\001 \001(\0102\206\001\n\rErrandService\022,\n\tnewErrand\022\016" +
      ".ErrandRequest\032\017.ErrandResponse\022G\n\020erran" +
      "dMedication\022\030.ErrandMedicationRequest\032\031.",
      "ErrandMedicationResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrandRequest_descriptor,
        new java.lang.String[] { "Deadline", });
    internal_static_ErrandResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ErrandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrandResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ErrandMedication_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ErrandMedication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrandMedication_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "ErrandId", });
    internal_static_ErrandMedicationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ErrandMedicationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrandMedicationRequest_descriptor,
        new java.lang.String[] { "ErrandMedications", });
    internal_static_ErrandMedicationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ErrandMedicationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrandMedicationResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
