package isa.apoteka.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrandService.proto

public interface ErrandMedicationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrandMedicationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool response = 1;</code>
   */
  boolean getResponse();
}
