package isa.apoteka.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrandService.proto

public interface ErrandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deadline = 1;</code>
   */
  java.lang.String getDeadline();
  /**
   * <code>string deadline = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeadlineBytes();
}
