package isa.apoteka.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrandService.proto

public interface ErrandMedicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrandMedication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>int32 errandId = 4;</code>
   */
  int getErrandId();
}
