package isa.apoteka.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrandService.proto

public interface ErrandMedicationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrandMedicationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ErrandMedication errandMedications = 1;</code>
   */
  java.util.List<ErrandMedication> 
      getErrandMedicationsList();
  /**
   * <code>repeated .ErrandMedication errandMedications = 1;</code>
   */
  ErrandMedication getErrandMedications(int index);
  /**
   * <code>repeated .ErrandMedication errandMedications = 1;</code>
   */
  int getErrandMedicationsCount();
  /**
   * <code>repeated .ErrandMedication errandMedications = 1;</code>
   */
  java.util.List<? extends ErrandMedicationOrBuilder> 
      getErrandMedicationsOrBuilderList();
  /**
   * <code>repeated .ErrandMedication errandMedications = 1;</code>
   */
  ErrandMedicationOrBuilder getErrandMedicationsOrBuilder(
      int index);
}
